"""add phone_number

Revision ID: 007384456e32
Revises: dafe64ee45c5
Create Date: 2022-01-09 13:03:03.626094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007384456e32'
down_revision = 'dafe64ee45c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
